[tool.poetry]
name = "websocket-with-fastapi"
version = "0.1.0"
description = "ğŸ¥®ğŸ¥®ğŸ¥® FastAPIã§WebSocketã‚’ä½¿ç”¨ã—ã¦ã¿ã‚‹ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
websockets = "^12.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
